### ISSUE TITLE
Pipeline feature

### ISSUE THREAD

**Issue by vmagamedov** [vmagamedov/pi#4]
```yaml
- !Pipeline
  name: make latte
  run:
    - power on
    - - - grind coffee
        - make espresso
        - clean
      - steam milk
    - merge
```
