### ISSUE TITLE
Tasks feature

### ISSUE THREAD

**Issue by vmagamedov** [vmagamedov/pi#5]
```yaml
- !Image
  name: env
  from: base
  repository: location/env
  provision-with: !Tasks
  - run: python3 {{get_pip_py}}
    where:
      get_pip_py: !Download "https://bootstrap.pypa.io/get-pip.py"
  - run: pip3 install {{packages|join(" ")}}
    where:
      packages:
        - requests==3.2
        - sqlalchemy==1.1
  - run: install -d {{src}} /path/to/src
    where:
      src: !Bundle "package"
```
