### ISSUE TITLE
Inline image definition

### ISSUE THREAD

**Issue by vmagamedov** [vmagamedov/pi#7]
Add ability to define `Image` in the `Command` definition, when this image will not be reused by another command, to place them together.

Prototype:

```yaml
- !Command
  name: version
  run: python3 --version
  image: !Image
    name: version
    from: !DockerImage alpine:3.4
    repository: reg.local/project.version
    tasks:
    - run: apk add --no-cache python3
```
